management:
  endpoints:
    web:
      base-path: "/my-blog"

spring:
  application:
    name: "myBlog"
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql

application:
  upload-dir: file:${MY_BLOG_UPLOADS_DIR}
  upload-url: "/uploads/"